use MEDIATE
GO

-- drop table MEDIATE..NE_SECTIONS_USER_ACCESS_RIGHTS
create table  NE_SECTIONS_USER_ACCESS_RIGHTS (
  SECTION_CODE    numeric(10,0)   not null,               --
  USER_CODE       numeric(5,0)   not null,               -- SECTION_CODE родителя
  DATE_CHANGE     datetime        not null                -- Дата последнего изменения

	--CONSTRAINT PK_SECTION_USER_CODE PRIMARY KEY CLUSTERED ( SECTION_CODE, USER_CODE )  on 'default'
)

create UNIQUE INDEX UI_NE_SECTIONS_USER_ACCESS_RIGHTS_USER ON NE_SECTIONS_USER_ACCESS_RIGHTS ( SECTION_CODE, USER_CODE )
go

ALTER TABLE MEDIATE.dbo.NE_SECTIONS_USER_ACCESS_RIGHTS
ADD CONSTRAINT FK_NE_SECTIONS_USER_ACCESS_RIGHTS_SECTION_CODE
FOREIGN KEY ( SECTION_CODE )
REFERENCES MEDIATE.dbo.NE_SECTIONS (SECTION_CODE)
go

ALTER TABLE MEDIATE.dbo.NE_SECTIONS_USER_ACCESS_RIGHTS
ADD CONSTRAINT FK_NE_SECTIONS_USER_ACCESS_RIGHTS_USER_CODE
FOREIGN KEY ( USER_CODE )
REFERENCES INTEGRAL.dbo.USERS (USER_CODE)
go