use MEDIATE
GO

-- drop table MEDIATE..NE_SECTIONS_ROLE_ACCESS_RIGHTS
create table  NE_SECTIONS_ROLE_ACCESS_RIGHTS (
  SECTION_CODE    numeric(10,0)   not null,               --
  ROLE_CODE       numeric(5,0)    not null,               -- INTEGRAL..PROPERTIES.PROP_CODE
  DATE_CHANGE     datetime        not null                -- Дата последнего изменения
)

create UNIQUE INDEX UI_NE_SECTIONS_ROLE_ACCESS_RIGHTS_USER ON NE_SECTIONS_ROLE_ACCESS_RIGHTS ( SECTION_CODE, ROLE_CODE )
go

ALTER TABLE MEDIATE.dbo.NE_SECTIONS_ROLE_ACCESS_RIGHTS
ADD CONSTRAINT FK_NE_SECTIONS_ROLE_ACCESS_RIGHTS_SECTION_CODE
FOREIGN KEY ( SECTION_CODE )
REFERENCES MEDIATE.dbo.NE_SECTIONS (SECTION_CODE)
go

ALTER TABLE MEDIATE.dbo.NE_SECTIONS_ROLE_ACCESS_RIGHTS
ADD CONSTRAINT FK_NE_SECTIONS_ROLE_ACCESS_RIGHTS_USER_CODE
FOREIGN KEY ( ROLE_CODE )
REFERENCES INTEGRAL.dbo.PROPERTIES (PROP_CODE)
go